project_id = "dwbhpjtnhmtdtmfxpacj"

[db]
major_version = 15 

[auth]
enabled = true
site_url = "https://dwbhpjtnhmtdtmfxpacj.lovableproject.com"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.email.template]

[functions.handle_new_user]
verify_jwt = false

[functions.insert-waitlist-submission]
verify_jwt = false

[functions.waitlist-submit]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-coach-subscription]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.complete-subscription]
verify_jwt = true

[functions.resend-coach-email]
verify_jwt = true

[functions.parse-workout-text]
verify_jwt = false

[functions.format-workout-notes]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000